name: Contributors by categories
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.contributors.categories.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  template: repository
  repo: metrics
  plugin_contributors: yes
  plugin_contributors_sections: categories
  plugin_contributors_categories: |
    {
      "🧩 Scripts":["scripts/**.sh", "**.sh"],
      "📚 Documentation":["README.md", "docs/index.md"],
      "💻 Code (other)":[".github/**", ".github/workflows/**"]
    }
